#cloud-config
package_update: true
package_upgrade: true
users:
    - name: deployer
      groups: [ sudo ]
      sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
      shell: /bin/bash
packages:
    - python
    - python-apt
    - python3-apt
    - build-essential
    - unzip
    - jq
    - git
    - apache2
snap:
    commands:
      00: snap install yq
      01: snap install slcli
final_message: "The system is finally up, after $UPTIME seconds"
output: {all: '| tee -a /var/log/cloud-init-output.log'}